services:
  # rocketask:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: nodejs
  #   container_name: rocketask
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - postgres

  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocketask
